<h1>Listado de usuarios</h1>
<hr class="colorgraph"/>

<table class="table table-striped list-users">
    <thead>
    <tr>
        <th>ID</th>
        <th>Usuario</th>
        <th>Mail</th>
        <th>Role</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user): ?>
        <tr>
            <td><?php echo $user->getId() ?></td>
            <td><a href="<?php echo $this->url('user/profile', array('id_user' => $user->getId())) ?>"><?php echo $user->getUsername() ?></a></td>
            <td><?php echo $user->getEmail() ?></td>
            <td><?php echo $user->getRole()->getName() ?></td>
            <td>
                <a class="btn btn-warning" href="#"><i class="fa fa-pencil-square-o fa-lg"></i> Editar</a>
                <a class="btn btn-danger" href="#"><i class="fa fa-trash-o fa-lg"></i> Eliminar</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>