<h1>Listado de usuarios</h1>
<hr class="colorgraph"/>

<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Usuario</th>
        <th>Mail</th>
        <th>Role</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user): ?>
        <tr>
            <td><?php echo $user->getIdUser() ?></td>
            <td><?php echo $user->getUsername() ?></td>
            <td><?php echo $user->getEmail() ?></td>
            <td><?php echo $user->getRole()->getName() ?></td>
            <td>
                <span class="glyphicon glyphicon-pencil"></span>
                <span class="glyphicon glyphicon-remove"></span>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>