<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="well clearfix">
                <div class="profile">
                    <div class="imgoutter">
                        <img src="/images/profile.jpg" alt="default"/>
                    </div>
                    <p>
                        <h4><?php echo $user->getName() ?> <?php echo $user->getLastname() ?></h4>
                        <h5><?php echo $user->getUsername() ?></h5>
                    </p>
                </div>
                <div class="profilebody">
                    <header>
                        <div class="row">

                        </div>
                    </header>
                    <section>
                        ID: <?php echo $user->getId() ?><br/>
                        Email: <?php echo $user->getEmail() ?><br/>
                        getUsername: <?php echo $user->getUsername() ?><br/>
                        getRole()->getName(): <?php echo $user->getRole()->getName() ?><br/>
                        getCity()->getName(): <?php echo $user->getCity()->getName() ?>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>