<?php
$form = $this->createForm;
$form->prepare();
$form->setAttribute('class', 'form');
$form->setAttribute('action', $this->url('user_register'));
?>

<div id="signup" class="panel panel-default col-md-8 col-md-offset-2">
    <h1>Register</h1>
    <hr class="colorgraph">
    <?php echo $this->form()->openTag($form) ?>
    <?php echo $this->renderForm($form); ?>
    <?php echo $this->form()->closeTag() ?>
</div>