<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('user_register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form')
?>

<div id="signup" class="panel panel-default col-md-8 col-md-offset-2">
    <h1>Register</h1>
    <hr class="colorgraph">
    <?php echo $this->form()->openTag($form) ?>
    <?php foreach ($form as $element): ?>
        <div class="form-group">
            <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
                <?php echo $this->formLabel($element) ?>
                <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
            <?php endif ?>
        </div>
        <div class="form-group">
            <?php if ($element instanceof Zend\Form\Element\Submit): ?>
                <?php echo $this->formButton($element) ?>
            <?php endif ?>
        </div>
    <?php endforeach ?>
    <?php echo $this->form()->closeTag() ?>
</div>