<h1>Register</h1>

<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('user_register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form')
?>

<?php echo $this->form()->openTag($form) ?>
    <?php foreach ($form as $element): ?>
        <div class="form-group">
            <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
                <?php echo $this->formLabel($element) ?>
                <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
            <?php endif ?>
        </div>
        <div class="form-group">
            <?php if ($element instanceof Zend\Form\Element\Submit): ?>
                <?php echo $this->formButton($element) ?>
            <?php endif ?>
        </div>
    <?php endforeach ?>
<?php echo $this->form()->closeTag() ?>