<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/bower_components/bootswatch/paper/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/bower_components/fontawesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/bower_components/custombox/dist/custombox.min.css')
        ->prependStylesheet($this->basePath() . '/css/delicious.css')
        ->prependStylesheet($this->basePath() . '/css/modal.login.css')
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->basePath('/') ?>">Delicious</a>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo $this->navigation('navigation')
                ->menu()
                ->setPartial('navigation/navigation.phtml')->__toString();
            ?>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
</div>
<!-- /container -->
<hr>
<footer>
    <p style="text-align: center">&copy; 2014 - <?php echo date('Y') ?>
        Delicious. <?php echo $this->translate('All rights reserved.') ?></p>
</footer>
<?php echo $this->inlineScript() ?>
<?php echo $this->headScript()
    ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
    ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
    ->appendFile($this->basePath() . '/bower_components/custombox/dist/custombox.min.js')
    ->appendFile($this->basePath() . '/bower_components/custombox/dist/legacy.min.js')
    ->appendFile($this->basePath() . '/js/delicious.js'); ?>
</body>
</html>
