<div class="modal-login">
    <button type="button" class="close" onclick="Custombox.close();">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>

    <div id="signin">
        <h1>Login</h1>
        <hr class="colorgraph">
        <form class="form-horizontal" data-action="/user/login">
            <fieldset>
                <div class="form-group">
                    <input type="email" name="email" id="email" class="form-control" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password">

                    <div class="checkbox pull-left">
                        <label>
                            <input type="checkbox" name="rememberme"/> Remember me
                        </label>
                    </div>
                    <div class="forgotpass pull-right"><a href="#">¿Has olvidado la contraseña?</a></div>
                </div>
            </fieldset>
            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a id="modalSignin" class="btn btn-lg btn-success btn-block">Sign In</a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a id="modalRegister" class="btn btn-lg btn-primary btn-block">Register</a>
                </div>
            </div>
        </form>
    </div>
</div>