<div class="jumbotron">
    <h1>Wellcome to Delicious!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquid, animi architecto beatae consectetur corporis eius est excepturi facilis impedit laudantium necessitatibus numquam officia provident quas ratione sit vero voluptas?</p>
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('bookmark') ?>">See the list of bookmarks</a></p>
</div>